apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  DATABASE_HOST: {{ .Values.DATABASE_HOST | quote }}
  DATABASE_PORT: {{ .Values.DATABASE_PORT }}
  DATABASE_USERNAME: {{ .Values.DATABASE_USERNAME | quote }}
  DATABASE_PASSWORD: {{ .Values.DATABASE_PASSWORD | quote }}
  DATABASE_NAME: {{ .Values.DATABASE_NAME | quote }}
  EXPIRED_DURATION: {{ .Values.EXPIRED_DURATION }}
  AGORA_APP_ID: {{ .Values.AGORA_APP_ID | quote }}
  AGORA_APP_CERTIFICATE: {{ .Values.AGORA_APP_CERTIFICATE | quote }}
  NETLESS_SDK_TOKEN: {{ .Values.NETLESS_SDK_TOKEN | quote }}
  NETLESS_APP_IDENTIFIER: {{ .Values.NETLESS_APP_IDENTIFIER | quote }}
  NETLESS_SDK_REGION: {{ .Values.NETLESS_SDK_REGION | quote }}